fruits = ["apple","banana","cherry"]
print("Initial List:",fruits)
fruits.append("orange")
fruits.insert(1,"mango")
print("After Adding Elements:",fruits)
fruits.remove("banana")
popped_item = fruits.pop()
print("After Removing Elements:",fruits)
print("Popped Item:",popped_item)
print("First fruit:",fruits[0])
print("Last fruit:",fruits[-1])
print("Sliced List (first two elements):",fruits[0:2])
fruits.sort()
print("Sorted List:",fruits)
fruits.reverse()
print("Reverse List:",fruits)
print("Number of fruits:",len(fruits))